name: Testing macOS

on: push

jobs:
  build:
    runs-on: macos-latest

    steps:
      - continue-on-error: false
      - uses: actions/checkout@master
      - name: Run install.sh
        run: bash ./install.sh
