name: Testing macOS

on: push

jobs:
  test:
    name: Install test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@master
      - name: Run install.sh
        run: sudo bash ./install.sh
